<template lang="html">
  <div class="container" style="background-color:#ecf0f1; width:95%;">
    <div class="row">
      <div class="col s3 m3" v-for='item in getAllitems'>
        <div class="card scale-up-center" @click='getDetailItem(item)' style="cursor:pointer;">
          <div class="card-image">
            <img :src="item.picture" style="width:100%; height:250px;">
          </div>
          <div class="card-content" style="height:50px; padding-bottom:20%;">
            <a><span class="card-title" style="font-size:16px;"> <b>{{ item.name }}</b> </span></a>
          </div>
          <div class="card-action">
            <h6 style="color:red;"> <b> Rp. {{ item.price.toLocaleString() }}</b></h6>
          </div>
          <div class="card-action" style="padding-left:8%;">
            <a class="btn red" style="width:100%;" v-if='isLogins == true && item.stock != 0' @click='addToCart(item)'>add to cart</a>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEdt34Dwuhb4i0TpxYd21MHzTtqtQ24pOki1-sgoPHf-_M8fhpDg" alt="" style="width:48.5%;" v-if='isLogins == true && item.stock == 0'>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  created () {
    this.checkLogin()
    this.getItem()
  },
  data () {
    return {
      items: null,
      isLogin: true,
      notification: true
    }
  },
  computed : {
    isLogins () {
      return this.$store.state.isLogin
    },
    getAllitems () {
      return this.$store.state.allItem
    }
  },
  methods: {
    checkLogin () {
      if (!localStorage.hasOwnProperty('authorization')) {
        this.$store.state.isLogin = false
      } else {
        this.$store.state.isLogin = true
      }
    },
    getItem () {
      axios({
        method: 'get',
        url: 'http://35.240.155.158/items'
      }).then(data => {
        const items = data.data.data
        this.$store.dispatch('getItems', items)
      }).catch(err => {
        console.log(err);
      })
    },
    addToCart (item) {
      const token = localStorage.getItem('authorization')

      if (!localStorage.hasOwnProperty('authorization')) {
        return false
      } else {
        this.$store.dispatch('addCart', item)
      }
    },
    getDetailItem (item){
      this.$store.dispatch('getDetail', item)
      this.$router.push(`/detail/${item._id}`)
    }
  }
}
</script>

<style lang="css">
.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-4 23:43:54
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

</style>
